// email.js
// Responder engine that sends email summaries using SMTP or SendGrid
// Supports both nodemailer (SMTP) and SendGrid API

const fs = require('fs');
const path = require('path');

module.exports = {
  async run(ctx, engineCfg, personaCfg) {
    const projectRoot = personaCfg.__projectRoot || process.cwd();
    const provider = String(engineCfg.provider || 'smtp').toLowerCase(); // 'smtp' or 'sendgrid'
    
    // Get email configuration
    const recipientEmail = engineCfg.to || process.env.EMAIL_TO;
    const subject = engineCfg.subject || 'AION Summary Report';
    const fromEmail = engineCfg.from || process.env.EMAIL_FROM;
    
    if (!shouldSendToday(engineCfg, new Date())) {
      console.log(`📧 Email responder: skipping send; today does not match sendOnDOW=${JSON.stringify(resolveSendOnDays(engineCfg))}`);
      return;
    }

    if (!recipientEmail) {
      console.error('❌ Email responder: no recipient specified. Set "to" in engine config or EMAIL_TO in .env');
      return;
    }
    
    // Extract content from passedFiles
    const content = extractContent(ctx.passedFiles, engineCfg);
    
    if (!content) {
      console.warn('⚠️ Email responder: no content to send');
      return;
    }

    try {
      if (provider === 'sendgrid') {
        await sendViaSendGrid(recipientEmail, subject, fromEmail, content, engineCfg);
      } else {
        await sendViaSMTP(recipientEmail, subject, fromEmail, content, engineCfg);
      }
    } catch (err) {
      console.error(`❌ Email responder failed: ${err.message}`);
      const sendGridErrors = err.response?.body?.errors;
      if (Array.isArray(sendGridErrors) && sendGridErrors.length) {
        sendGridErrors.forEach(error => {
          console.error(`❌ SendGrid detail: ${error.message}${error.field ? ` (field: ${error.field})` : ''}`);
        });
      }
    }
  }
};

async function sendViaSMTP(to, subject, from, content, engineCfg) {
  let nodemailer;
  try {
    nodemailer = require('nodemailer');
  } catch {
    throw new Error('nodemailer not installed. Run: npm install nodemailer');
  }

  const smtpHost = engineCfg.smtpHost || process.env.SMTP_HOST;
  const smtpPort = engineCfg.smtpPort || process.env.SMTP_PORT || 587;
  const smtpUser = engineCfg.smtpUser || process.env.SMTP_USER;
  const smtpPass = engineCfg.smtpPass || process.env.SMTP_PASS;
  const smtpSecure = engineCfg.smtpSecure !== false; // Default true for 465, false for 587

  if (!smtpHost || !smtpUser || !smtpPass) {
    throw new Error('SMTP config incomplete. Set SMTP_HOST, SMTP_USER, SMTP_PASS in .env');
  }

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpSecure,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  const mailOptions = {
    from: from || smtpUser,
    to,
    subject,
    html: content,
  };

  const info = await transporter.sendMail(mailOptions);
  console.log(`✅ Email sent via SMTP to ${to}. Message ID: ${info.messageId}`);
}

async function sendViaSendGrid(to, subject, from, content, engineCfg) {
  let sgMail;
  try {
    sgMail = require('@sendgrid/mail');
  } catch {
    throw new Error('@sendgrid/mail not installed. Run: npm install @sendgrid/mail');
  }

  const sendGridKey = engineCfg.sendGridKey || process.env.SENDGRID_API_KEY;
  if (!sendGridKey) {
    throw new Error('SendGrid API key not set. Set SENDGRID_API_KEY in .env or sendGridKey in engine config');
  }

  sgMail.setApiKey(sendGridKey);

  const msg = {
    to,
    from: from || process.env.EMAIL_FROM || 'noreply@aion.local',
    subject,
    html: content,
  };

  const response = await sgMail.send(msg);
  console.log(`✅ Email sent via SendGrid to ${to}. Status: ${response[0].statusCode}`);
}

function extractContent(passedFiles, engineCfg) {
  if (!Array.isArray(passedFiles) || passedFiles.length === 0) {
    return null;
  }

  const inputType = engineCfg.inputType; // Optional filter
  const files = inputType 
    ? passedFiles.filter(f => f.type === inputType)
    : passedFiles;

  if (files.length === 0) {
    return null;
  }

  // Build HTML email
  let html = '<html><body style="font-family: Arial, sans-serif;">';
  html += `<h1>${engineCfg.emailTitle || 'AION Report'}</h1>`;
  
  files.forEach(file => {
    html += `<h2>${file.name || file.type}</h2>`;
    if (file.documents && Array.isArray(file.documents)) {
      file.documents.forEach(doc => {
        const content = doc.content || '';
        // Simple markdown to HTML conversion (can be enhanced)
        const htmlContent = content
          .replace(/^## (.*?)$/gm, '<h3>$1</h3>')
          .replace(/^# (.*?)$/gm, '<h2>$1</h2>')
          .replace(/\n/g, '<br />');
        html += `<div>${htmlContent}</div>`;
      });
    }
  });

  html += '<hr />';
  html += `<p><small>Generated by AION on ${new Date().toISOString()}</small></p>`;
  html += '</body></html>';

  return html;
}

function shouldSendToday(engineCfg, date = new Date()) {
  const configured = resolveSendOnDays(engineCfg);
  const allowedDays = normalizeSendDays(configured);
  if (!allowedDays.length) return true;
  return allowedDays.includes(dayOfWeekNumber(date));
}

function resolveSendOnDays(engineCfg) {
  return engineCfg.sendOnDOW
    ?? engineCfg.sendOnDow
    ?? engineCfg.sendOnDayOfWeek
    ?? engineCfg.sendOnDays
    ?? engineCfg.sendOn;
}

function dayOfWeekNumber(date = new Date()) {
  return date.getDay() + 1; // 1=Sunday, 2=Monday, ... 7=Saturday
}

function normalizeSendDays(value) {
  if (value === undefined || value === null || value === '') return [];
  const values = Array.isArray(value)
    ? value
    : String(value).split(/[, ]+/).filter(Boolean);

  return values
    .map(dayToNumber)
    .filter(day => Number.isInteger(day) && day >= 1 && day <= 7);
}

function dayToNumber(value) {
  const text = String(value).trim().toLowerCase();
  const numeric = Number(text);
  if (Number.isInteger(numeric)) return numeric;
  const aliases = {
    sunday: 1,
    sun: 1,
    monday: 2,
    mon: 2,
    tuesday: 3,
    tue: 3,
    tues: 3,
    wednesday: 4,
    wed: 4,
    thursday: 5,
    thu: 5,
    thur: 5,
    thurs: 5,
    friday: 6,
    fri: 6,
    saturday: 7,
    sat: 7
  };
  return aliases[text];
}

module.exports._private = {
  dayOfWeekNumber,
  normalizeSendDays,
  resolveSendOnDays,
  shouldSendToday
};
